### PR TITLE
Rethink chains

### PR DESCRIPTION
**Pull request by zakarumych**
Total restructure chains design.
- [x] Support smart-scheduling. Pass only declares family on which it supposed to be executed. Scheduler will try to find best queue in the family
- [x] Make link to be collection of passes instead of single pass. Passes are collected into link as long as they all are able to use associated resource in parallel.
   Some links are limited to contain passes from only single queue. So they can perform resource ownership transfer.
- [x] Find semaphores and barriers required.
- [x] Optimize semaphores.
- [x] Prepare structures for command recoding and submitting.

---
This change is [Reviewable](https://reviewable.io/reviews/omni-viral/chains/4)

### CODE REVIEW

**Comment by Rhuagh** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4)*

**Comment by Rhuagh** [comment]
Reviewed 12 of 13 files at r2.
Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4)*

**Comment by Rhuagh** [comment]
Looks OK code wise, but I have no idea how to actually use the crate since there are no examples :)

**Comment by zakarumych** [comment]
@Rhuagh I guess I need to add examples to all those new crates :smile:

**Comment by torkleyy** [comment]
Reviewed 3 of 24 files at r1, 3 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/collect.rs, line 20 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wp7xZG15VbO8JxUS3:-L8Wp7x_9Z1aOYTj8yTV:b-gogmas) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L20)):*
> ```Rust
> 
> /// Placeholder for synchronization type.
> pub struct UnSynchronized;
> ```

This is a single word, so it should be `Unsynchronized`.

---

*[src/collect.rs, line 69 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WpbQ9VS24z65nblz7:-L8WpbQ9VS24z65nblz8:b-2efhmi) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L69)):*
> ```Rust
>         // Find passes that are ready to be enqueued
>         // E.g. All dependencies are enqueued.
>         enqueued.sort();
> ```

Can this be done only once, before the loop?

---

*[src/collect.rs, line 85 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WpnA-KLkUCj1Z907L:-L8WpnA-KLkUCj1Z907M:b-wdabsb) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L85)):*
> ```Rust
>                 (fitness, qid, index)
>             })
>             .min()
> ```

I think I'm not having the whole picture here, because it seems to me you could just sort these. Or what exactly changes during this loop?

---

*[src/pass.rs, line 25 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WrU7JO9_x_9a2iHm1:-L8WrU7JO9_x_9a2iHm2:byzirxq) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/pass.rs#L25)):*
> ```Rust
>     /// Dependencies of the pass.
>     /// Those are indices of other passes in array.
>     pub dependencies: Vec<usize>,
> ```

If you keep these dependencies sorted, the comparison (`all_there`) could be `O(n)` by just comparing element for element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4)*

**Comment by torkleyy** [comment]
I really like it :+1: :+1: 

---

Reviewed 10 of 24 files at r1, 8 of 13 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/resource/mod.rs, line 27 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WslZixpU7rRpKHcp_:-L8WslZjmSILOwXB-mFw:bbjarx) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/resource/mod.rs#L27)):*
> ```Rust
> /// Defines resource type.
> /// Should be implemented for buffers and images.
> pub trait Resource: Copy + Debug + Eq + Ord + Hash {
> ```

Why did you add all these bounds given that the implementors below don't even have values?

---

*[src/schedule/family.rs, line 42 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wt-_l0PoCZU1vGoET:-L8Wt-_l0PoCZU1vGoEU:b8acnqi) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L42)):*
> ```Rust
>     /// This function will panic if requested queue isn't part of this family.
>     ///
>     pub fn get_queue(&self, qid: QueueId) -> Option<&Queue<S>> {
> ```

`queue`

---

*[src/schedule/family.rs, line 53 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wt0ilpHvDl92TNGj7:-L8Wt0ilpHvDl92TNGj8:bdb071) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L53)):*
> ```Rust
>     /// This function will panic if requested queue isn't part of this family.
>     ///
>     pub fn get_queue_mut(&mut self, qid: QueueId) -> Option<&mut Queue<S>> {
> ```

`queue_mut`

---

*[src/schedule/family.rs, line 79 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wt4v1eJvpp4nTqAsW:-L8Wt4v1eJvpp4nTqAsX:blfwbzt) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L79)):*
> ```Rust
>     /// This function will panic if requested submit isn't part of this family.
>     ///
>     pub fn get_submit(&self, sid: SubmitId) -> Option<&Submit<S>> {
> ```

`submission`

---

*[src/schedule/family.rs, line 91 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WtOyyFQ_8HclOHX1M:-L8WtOyyFQ_8HclOHX1N:b-15uc6s) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L91)):*
> ```Rust
>     /// This function will panic if requested submit isn't part of this family.
>     ///
>     pub fn get_submit_mut(&mut self, sid: SubmitId) -> Option<&mut Submit<S>> {
> ```

`submission_mut`

---

*[src/schedule/family.rs, line 98 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WtVz7Q2lzEysonMgR:-L8WtVz7Q2lzEysonMgS:beoy0ec) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L98)):*
> ```Rust
> }
> 
> impl<S> Index<QueueId> for Family<S> {
> ```

Not sure about adding multiple `Index` operators to the same type, contributes little to code readability.

---

*[src/schedule/submit.rs, line 42 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WtKq7D6uUwEJk4ekH:-L8WtKq7D6uUwEJk4ekI:b6pp4tq) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/submit.rs#L42)):*
> ```Rust
> /// This type corresponds to commands that should be recorded into single primary command buffer.
> #[derive(Clone, Debug)]
> pub struct Submit<S> {
> ```

Maybe `Submission`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4#-:-L8WtjwhbEpLQqo7yR0_:bnmzlnp)*

**Comment by zakarumych** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/collect.rs, line 20 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wp7xZG15VbO8JxUS3:-L8WuPkegiVtnoyDduB0:b-79u1os) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L20)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

This is a single word, so it should be `Unsynchronized`.
</blockquote></details>

I should teach my Visual Studio Code some English then :smile: 
It marks `Unsynchronized` as grammar error.
Firefox does the same. Hmm...

---

*[src/collect.rs, line 69 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WpbQ9VS24z65nblz7:-L8WukLopwmhAxd5q3HS:brlhr1p) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L69)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Can this be done only once, before the loop?
</blockquote></details>

Before the loop it is empty.
And here the mistake.
I forgot to push the index there for each scheduled pass :smile: 

---

*[src/collect.rs, line 85 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WpnA-KLkUCj1Z907L:-L8Wvll1JUi4LF57-k-M:b-vfij60) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L85)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

I think I'm not having the whole picture here, because it seems to me you could just sort these. Or what exactly changes during this loop?
</blockquote></details>

Result of `fitness` depends on passes scheduled before. So it may change for each round of the loop.

---

*[src/pass.rs, line 25 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WrU7JO9_x_9a2iHm1:-L8WwPdsdGWtgw1SfuG1:bfp0zun) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/pass.rs#L25)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

If you keep these dependencies sorted, the comparison (`all_there`) could be `O(n)` by just comparing element for element.
</blockquote></details>

That's why I sort `enqueued`! Probably I got distracted and forgot it at some point.

---

*[src/resource/mod.rs, line 27 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WslZixpU7rRpKHcp_:-L8WwvEgYUwGX_whdDJV:b-xun5uz) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/resource/mod.rs#L27)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Why did you add all these bounds given that the implementors below don't even have values?
</blockquote></details>

To use `derive` for `Id<R>` and `State<R>`.
I know `Derivative` can handle this as well.

---

*[src/schedule/family.rs, line 98 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WtVz7Q2lzEysonMgR:-L8WxP5Vq4y8RHOXt990:bocpwfs) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L98)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Not sure about adding multiple `Index` operators to the same type, contributes little to code readability.
</blockquote></details>

It removes many `unwrap`s.

---

*[src/schedule/submit.rs, line 42 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WtKq7D6uUwEJk4ekH:-L8Wx_Q7i5UW0nub8e6J:bhy20no) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/submit.rs#L42)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Maybe `Submission`?
</blockquote></details>

Probably. Especially since this type now corresponds more to `gfx_hal::queue::Submission` more than to `gfx_hal::command::Submit`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4)*

**Comment by zakarumych** [comment]
I hope it'll work :laughing: 

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4#-:-L8Wy-Umguz3Ew0csISe:b8p2eny)*

**Comment by torkleyy** [comment]
Getters are still using nonstandard style (`get_foo` instead of `foo`), looks good otherwise.

---

Reviewed 2 of 14 files at r2, 3 of 12 files at r4.
Review status: 11 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/collect.rs, line 20 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wp7xZG15VbO8JxUS3:-L8X6ogzN9pLnalLhvph:b-k6olea) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L20)):*
<details><summary><i>Previously, omni-viral (Zakarum) wrote…</i></summary><blockquote>

I should teach my Visual Studio Code some English then :smile: 
It marks `Unsynchronized` as grammar error.
Firefox does the same. Hmm...
</blockquote></details>

According to dictionary.com it's a valid word: http://www.dictionary.com/browse/unsynchronized

---

*[src/collect.rs, line 85 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WpnA-KLkUCj1Z907L:-L8X7-4n0iJuePKAL80h:b-ayb5ty) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L85)):*
<details><summary><i>Previously, omni-viral (Zakarum) wrote…</i></summary><blockquote>

Result of `fitness` depends on passes scheduled before. So it may change for each round of the loop.
</blockquote></details>

OK, and yeah `enqueued` changes which I didn't know before.

---

*[src/collect.rs, line 109 at r4](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8X7WsdnA8OH1bOeuEF:-L8X7WseiPt0CGs2RO9K:bczsaez) ([raw file](https://github.com/omni-viral/chains/blob/e31e9fd882d4f40d59c9e81a2af499ba5d78c923/src/collect.rs#L109)):*
> ```Rust
> }
> 
> fn all_there(all: &[PassId], there: &[PassId]) -> bool {
> ```

The optimization is still TODO here

---

*[src/resource/mod.rs, line 27 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8WslZixpU7rRpKHcp_:-L8X7amuPnOw3lXmxUES:be9d9kw) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/resource/mod.rs#L27)):*
<details><summary><i>Previously, omni-viral (Zakarum) wrote…</i></summary><blockquote>

To use `derive` for `Id<R>` and `State<R>`.
I know `Derivative` can handle this as well.
</blockquote></details>

Hm, it's pretty confusing. I think `derivative` would indeed be better here. Maybe even a note above that this should be implemented for phantom types only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4#-:-L8X80y57lZuOYsZjl7i:b-644vu)*

**Comment by Lymia** [comment]
It looks like the concerns I brought up on Gitter are resolved too. :D

**Comment by zakarumych** [comment]
> Getters are still using nonstandard style (`get_foo` instead of `foo`)

Now they're not.

---

Review status: 11 of 20 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/collect.rs, line 20 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wp7xZG15VbO8JxUS3:-L8bkEpOIK2_xEEpitxi:b-896fix) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/collect.rs#L20)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

According to dictionary.com it's a valid word: http://www.dictionary.com/browse/unsynchronized
</blockquote></details>

Done.

---

*[src/schedule/family.rs, line 42 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wt-_l0PoCZU1vGoET:-L8bkD6MwZGwTzoSX7if:b-896fix) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L42)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

`queue`
</blockquote></details>

Done.

---

*[src/schedule/family.rs, line 53 at r3](https://reviewable.io:443/reviews/omni-viral/chains/4#-L8Wt0ilpHvDl92TNGj7:-L8bkCitbsy-SANPOGU-:b-896fix) ([raw file](https://github.com/omni-viral/chains/blob/f8c56142590d02ad65bbb9f67b0321f3821618f7/src/schedule/family.rs#L53)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

`queue_mut`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4#-:-L8bkLcGVkTkz0WUTK-h:bi630x8)*

**Comment by torkleyy** [comment]
Reviewed 1 of 14 files at r2, 9 of 12 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/chains/4)*

**Pull request merged**
